### ISSUE TITLE
Chrome Sync Support

### ISSUE THREAD

**Issue by Yifei0727** [EdmundLeex/github-notification#3]
Please use `chrome sync` for Sync settings on multiple computers 
 `chrome.storage.sync` and `chrome.storage.local`

**Comment by EdmundLeex** [comment]
@Yifei0727 Would you like to open a PR for this?

**Comment by Yifei0727** [comment]
👌

**Comment by Yifei0727** [comment]
before used chrome sync, 
1. need Permission `storage`
2. settings will overwrite
     defaults will set sync off, but first value load priority will be  
     * After Install, First Init    `chrome  cloud` > ~~`chrome local`~~ > `localStorage` > `defaults`
        and try copy cloud settings to localstorage
     * After Reset, All Values will be `defaults`, cloud settings will be cleared
     * changes will upgrade immediately
3.   if click `reset`, will reset all `chrome cloud` ... `localStorage`

---
page changes preview

![image](https://user-images.githubusercontent.com/6064040/48989823-f38f1980-f166-11e8-8ff5-bc025276e713.png)

**Comment by EdmundLeex** [comment]
@Yifei0727 If it needs extra permission, then you will need to change the [manifest.json](https://github.com/EdmundLeex/github-notification/blob/master/extension/manifest.json) file ([learn more here](https://developer.chrome.com/extensions/permission_warnings)). 

Since not everyone would need to sync, can you make it an optional feature so users can opt in to allow for the extra permission requirement?
